### ISSUE TITLE
Cached pages don't work correctly without session created by another app

### ISSUE THREAD

**Issue by warpech** [StarcounterApps/Content#34] opened 2017-04-18 16:40 UTC
### Steps to reproduce

1. Stop app apps
2. Start Content
3. Go to `/content/dynamic/index/header`

### Expected result

You should see the same as what you see when the SignIn app is started and you are signed in with the form `/signin/signinuser`

### Actual result

You get an exception:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Content.ContentHandlers.GetCachePage() in C:\www\Content\src\Content\Api\ContentHandlers.cs:line 52
   at Content.ContentHandlers.HandleWebContent(WebContent Item) in C:\www\Content\src\Content\Api\ContentHandlers.cs:line 65
   at Content.ContentHandlers.<Register>b__0_0(Request req, String query) in C:\www\Content\src\Content\Api\ContentHandlers.cs:line 21
   at lambda_method(Closure , Request , IntPtr , IntPtr )
   at Starcounter.Rest.UserHandlerInfo.RunUserDelegate(Request req, IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack) in C:\TeamCity\BuildAgent\work\sc-4704\Level1\src\Starcounter.Rest\UriHandlersManager.cs:line 346
   at Starcounter.Internal.Web.AppRestServer.RunDelegateAndProcessResponse(IntPtr methodSpaceUriSpaceOnStack, IntPtr parametersInfoOnStack, Request req) in C:\TeamCity\BuildAgent\work\sc-4704\Level1\src\Starcounter.Apps.JsonPatch\AppRestServer.cs:line 98
   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-4704\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 765
HResult=-2147467261

More information about this error may be available in the server error log.
```

##### Involved apps' version

StarcounterApps/Content@1c1d5d0275f188462f27c93589d7c0c5c77ae34b
StarcounterApps/SignIn@224070465b64212ac96fbce0f0a62e3e5eb90d84
 
##### Browsers affected

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Screenshot

![2017-04-18 17_04_10-localhost_8080_content_dynamic_index_header](https://cloud.githubusercontent.com/assets/566463/25137900/5879d876-2459-11e7-8f3b-c194f6a874e6.png)

**Comment by Mihaiii** [comment] 2017-06-21 22:11
For some reason, I can't reproduce. Went to those versions of SignIn and Content, but after I follow the instructions I get a "Content not found" page (btw, I think I'm missing something here: why should I see "the same as what you see when the SignIn app is started"? ).

@Mackiovello could you also please try to reproduce?

**Comment by Mackiovello** [comment] 2017-06-22 06:21
The Starcounter version doesn't matter.  It works differently now, but it's still possible to recreate: 
![cachingbug](https://user-images.githubusercontent.com/19392292/27419914-a7b2c810-5723-11e7-998f-af76525d9d7d.gif)

**Comment by Mihaiii** [comment] 2017-07-11 14:20
Closing as fixed.

**Closed by Mihaiii** 2017-07-11 14:20 UTC
Labels: bug
