### ISSUE TITLE
View option not working

### ISSUE THREAD

**Issue by bouguila** [StarcounterApps/Content#91] opened 2017-07-26 09:15 UTC
### Steps to reproduce
![content](https://user-images.githubusercontent.com/12608524/28613751-968f45a0-71f3-11e7-8aca-cc0b6d783fa1.gif)

##### Involved apps' version

 - StarcounterApps/Content -develop

**Comment by bouguila** [comment] 2017-07-26 09:15
Server log error:

System.Exception: ScErrSessionJsonNotRoot (SCERR14010): The json is not a rootobject (have no parent) and cannot be used as sessiondata.

Version: 2.3.1.6860.

Help page: https://github.com/Starcounter/Starcounter/wiki/SCERR14010.

   at Starcounter.Session.set_ClientRoot(Json value) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.XSON\Sessions\Session.cs:line 503

   at Starcounter.XSON.JsonMimeConverter.Convert(Json json, MimeType mimeType, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.XSON\Class Json\JsonMimeConverter.cs:line 52

   at Starcounter.Internal.ResourceMimeConverter.TryConvert(Request request, IResource resource, String mimeTypeStr, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:line 67

   at Starcounter.Internal.ResourceMimeConverter.Convert(Request request, Response response, String& resultingMimeType) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Apps.JsonPatch\BuiltInRestHandlers\ResourceMimeConverter.cs:line 46

   at Starcounter.Response.ConvertResource(Request req) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Internal\Http\Response.cs:line 765

   at Starcounter.Response.ConstructFromFields(Request req, Byte[] givenBuffer) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Internal\Http\Response.cs:line 821

   at Starcounter.Request.SendResponse(Response resp, Byte[] serializationBuf) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Internal\Http\Request.cs:line 1243

   at Starcounter.Internal.AppsBootstrapper.ProcessExternalRequest(Request req) in C:\TeamCity\BuildAgent\work\sc-6711\Level1\src\Starcounter.Apps.JsonPatch\AppsBootstrapper.cs:line 809

HResult=-2146233088

HelpLink=https://github.com/Starcounter/Starcounter/wiki/SCERR14010

**Comment by Mihaiii** [comment] 2017-07-26 09:29
Wow!
I reproduce this with the same Starcounter version you used: 2.3.1.6860 .

I downgraded Starcounter to 2.3.1.6707 and it works ok with it.
Is there a guide of changes that should be made in the code when one of the recent upgrade of Starcounter was made?

@warpech

**Comment by Mihaiii** [comment] 2017-07-27 00:32
It **works ok** with Starcounter version **2.3.1.6826** (and previous versions, I assume).
I gives the above **error** with Starcounter version **2.3.1.6839** (and further versions, I assume).

**Comment by warpech** [comment] 2017-07-27 16:49
This must be related to https://github.com/Starcounter/Announcements/issues/32. Please check that thread and https://github.com/Starcounter/Home/issues/139.

If you fail to find the cause, please ping me on Slack.

**Comment by warpech** [comment] 2017-08-01 11:46
Seems that exact same problem was detected in SignIn by @chrhol when he worked on the new Session changes (https://github.com/Starcounter/Announcements/issues/32).

See the PR in SignIn that fixed it: https://github.com/StarcounterApps/SignIn/pull/117, precisely: https://github.com/StarcounterApps/SignIn/commit/dd8edd6fc4de2a6d2bfbced7d7e0122748d48a62#diff-db8606ad459d9051ddcde2a085006721. Sadly, @chrhol didn't write any specific explanation for this.

**Comment by Mihaiii** [comment] 2017-08-04 14:35
Closing as solved.

**Closed by Mihaiii** 2017-08-04 14:35 UTC
Labels: P/High
